# setup modern mod_wsgi
# see http://askubuntu.com/questions/569550/assertionerror-using-apache2-and-libapache2-mod-wsgi-py3-on-ubuntu-14-04-python
    - name: install packages for wsgi_express
      apt:
        state: latest
        name: "{{ item }}"
      with_items:
        # for wsgi_express
        - apache2-dev
        - libpython3.4-dev
        - python3.4-venv
    - name: ensure certain packages are not installed
      apt:
        state: absent
        name: "{{ item }}"
      with_items:
        - libapache2-mod-wsgi-py3 # So as not to conflict with wsgi_express
    - script: py34_venv_with_pip.sh /srv/VENV/wsgiexpress creates=/srv/VENV/wsgiexpress
    - pip:
        name: mod_wsgi
        executable: /srv/VENV/wsgiexpress/bin/pip
    - command: /srv/VENV/wsgiexpress/bin/mod_wsgi-express install-module creates=/usr/lib/apache2/modules/mod_wsgi-py34.cpython-34m.so
    - copy:
        src: wsgi_express.conf
        dest: /etc/apache2/mods-available/wsgi_express.conf
      notify:
        restart httpd
    - copy:
        src: wsgi_express.load
        dest: /etc/apache2/mods-available/wsgi_express.load
      notify:
        restart httpd
    - apache2_module:
        name: wsgi_express
        state: present
